---
driver:
  name: terraform

provisioner:
  name: terraform

verifier:
  name: terraform
  systems:
    - name: basic
      attrs_outputs:
        client_ip1: client_ip1
        server_ip1: server_ip1
        server_ip2: server_ip2
        server_ip3: server_ip3
      backend: local

platforms:
  - name: terraform

suites:
  - name: default
